  tasks: 
    - name: Remove duplicate Elastic repo file if present
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/artifacts_elastic_co_packages_7_x_apt.list
        state: absent

    - name: Ensure prerequisites for APT over HTTPS
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Install Elastic GPG key into keyring
      ansible.builtin.shell: |
        set -e
        curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor | tee /usr/share/keyrings/elastic.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/elastic.gpg

    - name: Configure Elastic 7.x repo via Yandex mirror with signed-by
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/elastic-7x.list
        content: "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://mirror.yandex.ru/mirrors/elastic/7/ stable main\n"
        owner: root
        group: root
        mode: '0644'
 
    - name: Update apt cache (retry)
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update_result
      retries: 5
      delay: 5
      until: apt_update_result is succeeded
 
    - name: Install Elasticsearch (latest 7.x)
      ansible.builtin.apt:
        name: elasticsearch
        state: present

    - name: Enable and start Elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        enabled: yes
        state: started
