- name: Установка Elasticsearch
  hosts: elasticsearch
  become: yes

  tasks:
    - name: Ensure prerequisites for APT over HTTPS
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Add Elastic GPG key to keyring
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /usr/share/keyrings/elastic.gpg
        mode: '0644'

    - name: Add Elastic APT repository (7.x) with signed-by
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present
        filename: elastic-7x

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    # ВАЖНО: без пинования версии!
    - name: Install Elasticsearch (latest 7.x)
      ansible.builtin.apt:
        name: elasticsearch
        state: present 

    - name: Enable and start Elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        enabled: yes
        state: started 