all:
  vars:
    ansible_user: ubuntu

  children:
    webservers:
      hosts:
        web1.ru-central1.internal:
        web2.ru-central1.internal:

    elasticsearch:
      hosts:
        elasticsearch.ru-central1.internal:

    kibana:
      hosts:
        kibana-server.ru-central1.internal:

    zabbix:
      hosts:
        zabbix.ru-central1.internal:

