- name: Установка и настройка nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Установить nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Убедиться, что директория /var/www/html существует
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Положить кастомный index.html (с hostname)
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
        content: |
          <!doctype html>
          <html>
          <head><meta charset="utf-8"><title>My Site</title></head>
          <body style="font-family: sans-serif">
            <h1>It works 🎉</h1>
            <p>Served by: <b>{{ ansible_hostname }}</b></p>
          </body>
          </html>

    - name: Удалить дефолтную страницу Debian (если есть)
      ansible.builtin.file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

        # 1) Удаляем старый inline-блок, если был
    - name: Remove old inline stub_status block (if present)
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} managed by ansible (stub_status)"
        state: absent
      notify: Reload nginx

    # 2) Создаём сниппет с /nginx_status
    - name: Create snippet nginx_status.conf
      ansible.builtin.copy:
        dest: /etc/nginx/snippets/nginx_status.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          location /nginx_status {
              stub_status on; 
              allow 127.0.0.1;
              allow 10.0.0.0/8;
              deny all;
          }
      notify: Reload nginx

    # 3) Гарантируем единственную include-строку внутри server{}
    - name: Include snippet inside default server{}
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*include\s+snippets/nginx_status\.conf;'
        line: '    include snippets/nginx_status.conf;'
        insertafter: '^\s*server\s*\{'
      notify: Reload nginx

    # 4) Проверяем конфиг
    - name: Test nginx config
      ansible.builtin.command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
        enabled: yes
