- name: Установка и настройка nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Установить nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
 
    - name: Убедиться, что директория /var/www/html существует
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Положить кастомный index.html (с hostname)
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
        content: |
          <!doctype html>
          <html>
          <head><meta charset="utf-8"><title>My Site</title></head>
          <body style="font-family: sans-serif">
            <h1>It works 🎉</h1>
            <p>Served by: <b>{{ ansible_hostname }}</b></p>
          </body>
          </html>

    - name: Удалить дефолтную страницу Debian (если есть)
      ansible.builtin.file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

    # === ВКЛЮЧАЕМ stub_status ===
    - name: Включить stub_status в Nginx (локация /nginx_status)
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} managed by ansible (stub_status)"
        insertafter: '^\s*server\s*\{'
        block: |
          location /nginx_status {
              stub_status on;
              allow 10.0.0.0/8;
              deny all;
          }
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx 
        state: restarted
        enabled: yes
