- name: Установка Zabbix сервера
  hosts: zabbix
  become: yes

  vars:
    zabbix_major_version: "6.0"   # LTS
    zbx_codename: "focal"         # Ubuntu 20.04

  tasks:
    - name: Установить базовые зависимости для репозиториев
      ansible.builtin.apt:
        name:
          - gnupg
          - ca-certificates
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Добавить GPG-ключ репозитория Zabbix
      ansible.builtin.apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Подключить репозиторий Zabbix
      ansible.builtin.apt_repository:
        repo: "deb https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/ubuntu {{ zbx_codename }} main"
        state: present
        filename: zabbix

    - name: Обновить cache apt после добавления репозитория
      ansible.builtin.apt:
        update_cache: yes

    - name: Установить Zabbix server + web (Apache) и агент
      ansible.builtin.apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - mysql-client
        state: present
