- name: Add Zabbix repo GPG key
  ansible.builtin.apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Add Zabbix APT repository (6.0 LTS for Ubuntu 20.04 Focal)
  ansible.builtin.apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.0/ubuntu focal main"
    state: present
    filename: "zabbix"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix server and web frontend (Apache)
  ansible.builtin.apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
      - mysql-client
    state: present
